//
// Created by ben on 5/26/24.
//

#ifndef PLATFORMER_PHYSICSCONSTANTS_H
#define PLATFORMER_PHYSICSCONSTANTS_H

#define GRAVITY 45
#define FRICTION 85
#define MAX_VELOCITY 50

#endif //PLATFORMER_PHYSICSCONSTANTS_H
