//
// Created by ben on 8/1/24.
//

#ifndef PLATFORMER_EVENTS_H
#define PLATFORMER_EVENTS_H

enum Events {
    EVENT_PLAYER_JUMPED,
    EVENT_PLAYER_ATTACK,
    EVENT_PLAYER_LANDED
};

#endif //PLATFORMER_EVENTS_H